let config = require("./config").config;

var forgotPasswordMailTemplate = {
  from: '"Reset Password | Errepar test sample" <test@gmail.com>',
  subject: " Olvido su password ",
  html: '<!doctype html><html><head><title>Reset Password | Errepar test sample</title><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0; padding:0;"><div style="max-width:850px; margin:auto;"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0"><tr><td><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr><td align="center" style="font-size:16px; padding:20px 0; font-family:arial; background:#000;"><img src="{{baseUrl}}/assets/images/logo.png" width="281" height="80" alt="" /></td></tr></table></td></tr><tr><td valign="top"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="text-align:center; border:1px solid #ff9545; line-height:24px;"><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;"> Bienvenidos !</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Lorem Ipsum. {{email}}. Haga click en el botton para activar y poder loguear.</td></tr><tr><td style="padding:10px;"><div style="font-size:16px; font-family:arial; font-weight:bold; background-color:#ff9545;color:#fff; padding:10px;"><a href="{{link}}" target="_blank">Reset Password</a></div></td></tr><tr><td style="font-size:16px; padding:10px; font-family:arial;">Tambien puede copiar y pegar:</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;"><a href="#">{{link}}</a> </td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Gracias,</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Errepar Test</td></tr><tr><td height="10"></td></tr></table></td></tr></table></div></body></html>',
};

var activationMailTemplate = {
  from: '"Errepar test sample" <testr@gmail.com>',
  subject: " Activacion de cuenta ",
  html: '<!doctype html><html><head><title>Errepar test sample</title><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0; padding:0;"><div style="max-width:850px; margin:auto;"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0"><tr><td><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr><td align="center" style="font-size:16px; padding:20px 0; font-family:arial; background:#000;"><img src="{{baseUrl}}/assets/images/logo.png" width="281" height="80" alt="" /></td></tr></table></td></tr><tr><td valign="top"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="text-align:center; border:1px solid #ff9545; line-height:24px;"><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;"> Bienvenido sea !</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Lorem Ipsum.  {{email}}. Haga click en el botton para activar y poder loguear.</td></tr><tr><td style="padding:10px;"><div style="font-size:16px; font-family:arial; font-weight:bold; background-color:#ff9545;color:#fff; padding:10px;"><a href="{{link}}" target="_blank">Verificacion Email</a></div></td></tr><tr><td style="font-size:16px; padding:10px; font-family:arial;">Puede copiar y pegar, si quiere:</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;"><a href="#">{{link}}</a> </td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Gracias,</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Errepar Test</td></tr><tr><td height="10"></td></tr></table></td></tr></table></div></body></html>',
};

module.exports = {
  activationMailTemplate: activationMailTemplate,
  forgotPasswordMailTemplate: forgotPasswordMailTemplate,
};
